deploy_production:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rev --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"
  environment:
    name: production
    url: https://socialhouse.top
  only:
    - main
    